version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./docker/.env.local
    depends_on:
      - db
      - cache
    entrypoint: tail -f /dev/null

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ireland_ie
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    build: ./docker/nginx
    volumes:
      - static_volume:/app/static
    ports:
      - 80:80
    depends_on:
      - web

  cache:
    image: redis:6.2-alpine

volumes:
  postgres_data:
  static_volume:
