# Generated by Django 3.2.10 on 2023-11-28 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cib_images', '0002_initial'),
        ('cib_home', '0006_alter_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='A short one-sentence literal description\n                    of the %s is\n                    required to make the page accessible to the\n                    visually impaired. Details: https://axesslab.com/alt-texts/', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cib_images.customimage'),
        ),
    ]
