# Generated by Django 3.2.10 on 2023-11-29 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('wagtailforms', '0005_alter_formsubmission_form_data'),
        ('wagtailredirects', '0008_add_verbose_name_plural'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('cib_home', '0008_boardpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoardPage',
        ),
    ]
