# Generated by Django 3.2.10 on 2023-11-30 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cib_home', '0009_delete_boardpage'),
        ('cib_home', '0011_alter_homepage_hero_double_feature'),
    ]

    operations = [
    ]
