# Generated by Django 3.2.10 on 2023-11-30 11:39

import cib_home.blocks
from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cib_home', '0012_merge_20231130_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='callout_feature',
            field=wagtail.fields.StreamField([('CalloutCards', wagtail.blocks.StructBlock([('calloutcards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(help_text='The Icon size should be 55x55 pixels', required=False)), ('title', wagtail.blocks.CharBlock(required=True)), ('text', wagtail.blocks.RichTextBlock(required=True)), ('button_page', wagtail.blocks.PageChooserBlock(help_text='This button has higher priority than button_url', required=False)), ('button_url', wagtail.blocks.URLBlock(required=False)), ('button_text', wagtail.blocks.CharBlock(required=True)), ('left_border_color', cib_home.blocks.ColorChooserBlock(required=True))])))]))], blank=True, use_json_field=None),
        ),
    ]
