# Generated by Django 3.2.10 on 2023-12-04 11:45

from django.db import migrations
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cib_home', '0015_alter_homepage_hero_double_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='newslettersignupcta',
            field=wagtail.fields.StreamField([('newslettersignupcta_snippet', wagtail.snippets.blocks.SnippetChooserBlock(target_model='utils.NewsletterSignUpCTASnippet'))], null=True, use_json_field=None),
        ),
    ]
