# Generated by Django 3.2.10 on 2023-12-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cib_home', '0016_homepage_newslettersignupcta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='newslettersignupcta',
            new_name='news_letter_signup_cta',
        ),
    ]
