# Generated by Django 3.2.10 on 2023-12-14 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cib_home', '0019_homepage_last_published_custom'),
        ('cib_home', '0020_auto_20231213_1307'),
    ]

    operations = [
    ]
