# Generated by Django 3.2.10 on 2023-12-15 15:36

import cib_home.blocks
from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cib_home', '0021_merge_20231214_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('CalloutCards', wagtail.blocks.StructBlock([('calloutcards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(help_text='The Icon size should be 55x55 pixels', required=False)), ('icon_alt', wagtail.blocks.CharBlock(help_text='The alt text shown for accessibility: https://axesslab.com/alt-texts/', required=True)), ('title', wagtail.blocks.CharBlock(required=True)), ('text', wagtail.blocks.RichTextBlock(required=True)), ('button_page', wagtail.blocks.PageChooserBlock(help_text='This button has higher priority than button_url', required=False)), ('button_url', wagtail.blocks.URLBlock(required=False)), ('button_text', wagtail.blocks.CharBlock(required=True)), ('left_border_color', cib_home.blocks.ColorChooserBlock(required=True))]), max_num=3))])), ('InfoPanelCards', wagtail.blocks.StructBlock([('infocards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(help_text='The Icon size should be 60x60 pixels', required=False)), ('icon_alt', wagtail.blocks.CharBlock(help_text='The alt text shown for accessibility: https://axesslab.com/alt-texts/', required=True)), ('title', wagtail.blocks.CharBlock(required=True)), ('text', wagtail.blocks.RichTextBlock(required=True)), ('button_page', wagtail.blocks.PageChooserBlock(help_text='This button has higher priority than button_url', required=False)), ('button_url', wagtail.blocks.URLBlock(required=False)), ('button_text', wagtail.blocks.CharBlock(required=True))])))])), ('JobVacanciesAndNewsCard', wagtail.blocks.StructBlock([('job_vacancies', wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(help_text='The Icon size should be 60x60 pixels', required=False)), ('icon_alt', wagtail.blocks.CharBlock(help_text='The alt text shown for accessibility: https://axesslab.com/alt-texts/', required=True)), ('vacancy_title', wagtail.blocks.CharBlock(required=True)), ('vacancy_text', wagtail.blocks.RichTextBlock(required=True)), ('vacancy_button_page', wagtail.blocks.PageChooserBlock(help_text='This button has higher priority than button_url', required=False)), ('vacancy_button_url', wagtail.blocks.URLBlock(required=False)), ('vacancies_button_text', wagtail.blocks.CharBlock(help_text='Job vacancies button text', required=True)), ('vacancies_background_color', cib_home.blocks.ColorChooserBlock(help_text='Set the Job vacancies background color', required=True))])), ('news_card', wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(help_text='The Icon size should be 60x60 pixels', required=False)), ('icon_alt', wagtail.blocks.CharBlock(help_text='The alt text shown for accessibility: https://axesslab.com/alt-texts/', required=True)), ('block_title', wagtail.blocks.CharBlock(required=True)), ('news_button_text', wagtail.blocks.CharBlock(help_text='News card button text', required=True)), ('news_Background_color', cib_home.blocks.ColorChooserBlock(help_text='Set the News background color', required=True))]))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
