# Generated by Django 3.2.10 on 2023-12-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cib_home', '0023_homepage_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='summary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
