# Generated by Django 3.2.10 on 2023-12-08 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20231208_1130'),
    ]

    operations = [
    ]
