# Generated by Django 3.2.10 on 2024-01-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cib_board', '0004_boardpage_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardpage',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
