# Generated by Django 3.2.10 on 2024-01-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cib_board', '0006_boardpage_left_nav_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardpage',
            name='summary',
            field=models.TextField(blank=True, help_text='Summary text to appear under search results', null=True),
        ),
    ]
