# Generated by Django 3.2.10 on 2023-12-15 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cib_news_content_page', '0003_newscontentpage_lead_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscontentpage',
            name='banner_image',
        ),
    ]
