# Generated by Django 3.2.10 on 2023-12-18 09:34

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cib_news_content_page', '0004_remove_newscontentpage_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscontentpage',
            name='lead_fields',
            field=wagtail.fields.StreamField([('banner_image', wagtail.blocks.StructBlock([('image_file', wagtail.images.blocks.ImageChooserBlock(help_text='', label='Image')), ('alt_text', wagtail.blocks.CharBlock(label='Alt', required=False))])), ('lead_text', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'document-link'], required=True))], null=True, use_json_field=True),
        ),
    ]
