# Generated by Django 3.2.10 on 2023-12-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cib_news_content_page', '0005_alter_newscontentpage_lead_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstag',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='newstag',
            name='locale',
            field=models.CharField(blank=True, default='en', max_length=10, null=True),
        ),
    ]
