# Generated by Django 3.2.10 on 2023-12-18 14:37

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cib_content_page', '0003_contentpage_last_published_custom'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobVacanciesTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'job vacancy tag',
                'verbose_name_plural': 'job vacancies tags',
            },
        ),
        migrations.CreateModel(
            name='JobVacancyContentPage',
            fields=[
                ('contentpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cib_content_page.contentpage')),
                ('job_vacancy_tags', modelcluster.fields.ParentalManyToManyField(blank=True, to='cib_jobs.JobVacanciesTag')),
            ],
            options={
                'abstract': False,
            },
            bases=('cib_content_page.contentpage',),
        ),
        migrations.CreateModel(
            name='TaggedJobVacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_jobvacancies_items', to='cib_jobs.jobvacancycontentpage')),
                ('tag', models.ForeignKey(help_text='news tags', on_delete=django.db.models.deletion.CASCADE, related_name='tagged_jobvacancies', to='cib_jobs.jobvacanciestag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
