# Generated by Django 3.2.10 on 2023-12-18 16:12

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('cib_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancycontentpage',
            name='address',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobvacancycontentpage',
            name='contact_email',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobvacancycontentpage',
            name='job_description',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobvacancycontentpage',
            name='job_forms',
            field=wagtail.fields.StreamField([('heading_with_document', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(help_text='Enter your heading text', required=True)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=True))]))], null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='jobvacancycontentpage',
            name='job_title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobvacancycontentpage',
            name='organisation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobvacancycontentpage',
            name='organisation_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='jobvacancycontentpage',
            name='organisation_logo_alt',
            field=models.CharField(blank=True, help_text='The alt text shown for accessibility: https://axesslab.com/alt-texts/', max_length=255, verbose_name='Image Alt text'),
        ),
    ]
