# Generated by Django 3.2.10 on 2023-12-18 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cib_images', '0002_initial'),
        ('cib_jobs', '0002_auto_20231218_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancycontentpage',
            name='organisation_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cib_images.customimage'),
        ),
    ]
