# Generated by Django 3.2.10 on 2023-12-19 09:19

from django.db import migrations, models
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cib_jobs', '0003_alter_jobvacancycontentpage_organisation_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancycontentpage',
            name='closing_date_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jobvacancycontentpage',
            name='job_forms',
            field=wagtail.fields.StreamField([('heading_with_document', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(help_text='Enter your heading text', required=True)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=True))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
