# Generated by Django 3.2.10 on 2023-12-19 11:52

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_jobsvacanciesandlatestnewssnippet'),
        ('cib_jobs', '0005_auto_20231219_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancycontentpage',
            name='jobvacancy_latestnews_snippet',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='utils.JobsVacanciesAndLatestNewsSnippet'),
        ),
    ]
