# Generated by Django 3.2.10 on 2023-12-20 10:03

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('cib_jobs', '0007_auto_20231219_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobVacanciesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('publication_log', wagtail.fields.RichTextField(blank=True, help_text='Put your comment for current changes', null=True, verbose_name='publication_log')),
                ('last_published_custom', models.DateField(blank=True, help_text="Can be used to override the Wagtail-managed 'last published at' datetime, making content appear older (or newer) than it really is.", null=True, verbose_name='last publish date (custom)')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='jobvacancycontentpage',
            name='job_index_lead_summary',
            field=models.TextField(help_text='A brief 1-2 sentence job summary. This will appear on the job vacancy index page, not on the job posting itself.', max_length=300, null=True),
        ),
    ]
