# Generated by Django 3.2.10 on 2024-01-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cib_jobs', '0010_auto_20231220_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacanciespage',
            name='summary',
            field=models.TextField(blank=True, help_text='Summary text to appear under search results', null=True),
        ),
    ]
