# Generated by Django 3.2.10 on 2024-01-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cib_jobs', '0011_jobvacanciespage_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancycontentpage',
            name='show_on_page',
            field=models.BooleanField(null=True),
        ),
    ]
