# Generated by Django 3.2.10 on 2024-01-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cib_jobs', '0012_jobvacancycontentpage_show_on_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobvacancycontentpage',
            name='jobvacancy_latestnews_snippet',
        ),
    ]
