# Generated by Django 3.2.10 on 2024-01-18 10:08

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cib_jobs', '0013_remove_jobvacancycontentpage_jobvacancy_latestnews_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacanciespage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
