# Generated by Django 3.2.10 on 2023-12-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cib_news_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='last_published_custom',
            field=models.DateField(blank=True, help_text="Can be used to override the Wagtail-managed 'last published at' datetime, making content appear older (or newer) than it really is.", null=True, verbose_name='last publish date (custom)'),
        ),
    ]
