# Generated by Django 3.2.10 on 2023-12-21 18:05

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cib_news_page', '0002_news_last_published_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='publication_select_component',
            field=wagtail.fields.StreamField([('news_tag_select_component', wagtail.blocks.StructBlock([('select_title', wagtail.blocks.CharBlock(max_length=50)), ('select_hint_text', wagtail.blocks.CharBlock(max_length=50, required=False)), ('select_default_option_value', wagtail.blocks.CharBlock(max_length=50))]))], null=True, use_json_field=None),
        ),
        migrations.AddField(
            model_name='news',
            name='year_select_component',
            field=wagtail.fields.StreamField([('year_select_component', wagtail.blocks.StructBlock([('select_title', wagtail.blocks.CharBlock(max_length=50)), ('select_hint_text', wagtail.blocks.CharBlock(max_length=50, required=False)), ('select_default_option_value', wagtail.blocks.CharBlock(max_length=50))]))], null=True, use_json_field=None),
        ),
    ]
