# Generated by Django 3.2.10 on 2024-01-02 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cib_news_page', '0003_news_summary'),
        ('cib_news_page', '0004_rename_publication_select_component_news_news_tag_select_component'),
    ]

    operations = [
    ]
