# Generated by Django 3.2.10 on 2024-01-18 11:56

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cib_news_page', '0006_auto_20240112_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
