# Generated by Django 3.2.10 on 2023-12-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cib_content_page', '0004_auto_20231218_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetag',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='pagetag',
            name='locale',
            field=models.CharField(blank=True, default='en', max_length=10, null=True),
        ),
    ]
