# Generated by Django 3.2.10 on 2024-01-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cib_content_page', '0006_contentpage_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='left_nav_title',
            field=models.TextField(null=True),
        ),
    ]
