# Generated by Django 3.2.10 on 2024-01-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cib_content_page', '0007_contentpage_left_nav_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='left_nav_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
