# Generated by Django 3.2.10 on 2024-01-15 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_jobsvacanciesandlatestnewssnippet'),
        ('cib_content_page', '0009_auto_20240112_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='jobvacancy_latest_news_snippet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='utils.jobsvacanciesandlatestnewssnippet'),
        ),
    ]
