# Generated by Django 3.2.10 on 2024-01-12 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cib_content_page', '0010_contentpage_jobvacancy_latestnews_snippet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentpage',
            old_name='jobvacancy_latestnews_snippet',
            new_name='jobvacancy_latest_news_snippet',
        ),
    ]
