# Generated by Django 3.2.10 on 2023-12-14 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cib_pages', '0006_alter_freeformpage_body'),
        ('cib_pages', '0006_freeformpage_last_published_custom'),
    ]

    operations = [
    ]
