# Generated by Django 3.2.10 on 2024-01-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cib_pages', '0009_auto_20240112_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeformpage',
            name='left_nav_title',
            field=models.TextField(null=True),
        ),
    ]
