# Generated by Django 3.2.10 on 2024-04-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cib_pages', '0012_alter_freeformpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeformpage',
            name='show_left_nav_title',
            field=models.BooleanField(default=True, verbose_name='Show left nav title'),
        ),
    ]
