# Generated by Django 3.2.10 on 2023-11-17 11:12

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import taggit.managers
import uuid
import wagtail.blocks
import wagtail.fields
import wagtail.models
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('cib_images', '0002_initial'),
        ('wagtailcore', '0078_referenceindex'),
        ('cib_navigation', '0002_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterNavigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('live', models.BooleanField(default=True, editable=False, verbose_name='live')),
                ('has_unpublished_changes', models.BooleanField(default=False, editable=False, verbose_name='has unpublished changes')),
                ('first_published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at')),
                ('last_published_at', models.DateTimeField(editable=False, null=True, verbose_name='last published at')),
                ('go_live_at', models.DateTimeField(blank=True, null=True, verbose_name='go live date/time')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time')),
                ('expired', models.BooleanField(default=False, editable=False, verbose_name='expired')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('lang', models.CharField(help_text="Internal name for this navigation, it's not displayed to a site user.", max_length=255, unique=True, verbose_name='Language')),
                ('logo_alt', models.CharField(help_text='A short one-sentence literal description\n                    of the image is\n                    required to make the page accessible to the\n                    visually impaired. Details: https://axesslab.com/alt-texts/', max_length=255, verbose_name='Logo Alt text')),
                ('navigation', wagtail.fields.StreamField([('column', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(help_text='Leave blank if no header required.', required=False)), ('links', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=False)), ('title', wagtail.blocks.CharBlock(help_text="Leave blank to use the page's own title", required=False)), ('url', wagtail.blocks.URLBlock(help_text='An external link.', label='URL', required=False))])))]))], blank=True, help_text='Multiple columns of footer links with optional header.', use_json_field=None, verbose_name='Columns')),
                ('links', wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=False)), ('title', wagtail.blocks.CharBlock(help_text="Leave blank to use the page's own title", required=False)), ('url', wagtail.blocks.URLBlock(help_text='An external link.', label='URL', required=False))]))], blank=True, help_text='Single list of elements at the base of the page.', use_json_field=None)),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('live_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='live revision')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cib_images.customimage')),
            ],
            options={
                'verbose_name': 'Footer Navigation',
                'verbose_name_plural': 'Footer Navigation',
            },
            bases=(wagtail.models.PreviewableMixin, wagtail.search.index.Indexed, models.Model),
        ),
        migrations.AlterField(
            model_name='primarynavigation',
            name='navigation',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=False)), ('title', wagtail.blocks.CharBlock(help_text="Leave blank to use the page's own title", required=False)), ('url', wagtail.blocks.URLBlock(help_text='An external link.', label='URL', required=False))]))], blank=True, help_text='Main site navigation', use_json_field=True, verbose_name='Links'),
        ),
        migrations.CreateModel(
            name='FooterNavigationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='cib_navigation.footernavigation')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cib_navigation_footernavigationtag_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='footernavigation',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='cib_navigation.FooterNavigationTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterUniqueTogether(
            name='footernavigation',
            unique_together={('translation_key', 'locale')},
        ),
    ]
