# Generated by Django 3.2.10 on 2023-11-28 11:48

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cib_navigation', '0005_alter_footernavigation_navigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarynavigation',
            name='popular_links',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=False)), ('title', wagtail.blocks.CharBlock(help_text="Leave blank to use the page's own title", required=False)), ('url', wagtail.blocks.URLBlock(help_text='An external link.', label='URL', required=False))]))], blank=True, help_text='Main site navigation', use_json_field=True, verbose_name='Links'),
        ),
    ]
