# Generated by Django 3.2.10 on 2024-01-03 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cib_images', '0002_initial'),
        ('cib_navigation', '0007_alter_primarynavigation_popular_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='site_logo',
            new_name='site_english_logo',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_irish_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cib_images.customimage'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_irish_logo_alt',
            field=models.CharField(help_text='A short one-sentence literal description\n                    of the image is\n                    required to make the page accessible to the\n                    visually impaired. Details: https://axesslab.com/alt-texts/', max_length=255, null=True, verbose_name='Logo Alt text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_logo_alt',
            field=models.CharField(help_text='A short one-sentence literal description\n                    of the image is\n                    required to make the page accessible to the\n                    visually impaired. Details: https://axesslab.com/alt-texts/', max_length=255, null=True, verbose_name='Logo Alt text'),
        ),
    ]
