# Generated by Django 3.2.10 on 2024-01-04 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cib_images', '0002_initial'),
        ('cib_navigation', '0009_rename_site_logo_alt_sitesettings_site_english_logo_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_english_logo',
            field=models.ForeignKey(blank=True, help_text='The image size should be 255x71 pixels', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cib_images.customimage'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_irish_logo',
            field=models.ForeignKey(blank=True, help_text='The image size should be 255x71 pixels', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cib_images.customimage'),
        ),
    ]
