# Generated by Django 3.2.10 on 2024-01-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cib_navigation', '0010_auto_20240104_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='pagination_count',
            field=models.IntegerField(default=10),
        ),
    ]
