# Generated by Django 3.2.10 on 2024-01-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cib_navigation', '0011_sitesettings_pagination_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footernavigation',
            name='lang',
        ),
    ]
