# Generated by Django 3.2.10 on 2024-01-09 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cib_navigation', '0012_remove_footernavigation_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='footernavigation',
            name='lang',
            field=models.CharField(default=django.utils.timezone.now, help_text="Internal name for this navigation, it's not displayed to a site user.", max_length=255, unique=True, verbose_name='Language'),
            preserve_default=False,
        ),
    ]
