# Generated by Django 3.2.10 on 2024-01-10 13:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cib_navigation', '0014_remove_footernavigation_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='footernavigation',
            name='lang',
            field=models.CharField(default=uuid.uuid1, help_text="Internal name for this navigation, it's not displayed to a site user.", max_length=255, unique=True, verbose_name='Language'),
        ),
    ]
