# Generated by Django 3.2.10 on 2024-03-04 16:24

import cib_navigation.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cib_navigation', '0018_alter_primarynavigation_navigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='footernavigation',
            name='facebook_app_id',
            field=models.CharField(blank=True, help_text='Your Facebook app ID.', max_length=255, validators=[cib_navigation.mixins.validate_hostname]),
        ),
        migrations.AddField(
            model_name='footernavigation',
            name='instagram_user',
            field=models.CharField(blank=True, help_text='Your Instagram username.', max_length=255, validators=[cib_navigation.mixins.validate_hostname]),
        ),
        migrations.AddField(
            model_name='footernavigation',
            name='linkedin_profile',
            field=models.URLField(blank=True, help_text='Your LinkedIn profile URL.'),
        ),
        migrations.AddField(
            model_name='footernavigation',
            name='twitter_handle',
            field=models.CharField(blank=True, help_text='Your Twitter username without the @, e.g. katyperry', max_length=255, validators=[cib_navigation.mixins.validate_hostname]),
        ),
        migrations.AddField(
            model_name='footernavigation',
            name='vimeo_user',
            field=models.CharField(blank=True, help_text='Your Vimeo username.', max_length=255, validators=[cib_navigation.mixins.validate_hostname]),
        ),
        migrations.AddField(
            model_name='footernavigation',
            name='youtube_user',
            field=models.CharField(blank=True, help_text='Your YouTube username.', max_length=255, validators=[cib_navigation.mixins.validate_hostname]),
        ),
    ]
