# Generated by Django 3.2.10 on 2023-12-06 12:27

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cib_documents', '0004_documentpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttypetag',
            options={'verbose_name': 'Publication Type Tag', 'verbose_name_plural': 'Publication Type Tags'},
        ),
        migrations.AlterField(
            model_name='documentpage',
            name='body',
            field=wagtail.fields.StreamField([('document', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.RichTextBlock(required=True)), ('language', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(required=True)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=True))]), label='Languages', required=True)), ('year_tags', wagtail.blocks.ChoiceBlock(choices=[('2023', '2023'), ('2024', '2024')], label='Year Tags', required=False)), ('Publication_type_tags', wagtail.blocks.ChoiceBlock(choices=[], label='Document Type Tags', required=False))]))], blank=True, use_json_field=None),
        ),
    ]
