# Generated by Django 3.2.10 on 2023-12-06 14:43

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cib_documents', '0005_auto_20231206_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpage',
            name='publication_log',
            field=wagtail.fields.RichTextField(blank=True, help_text='Put your comment for current changes', null=True, verbose_name='publication_log'),
        ),
        migrations.AlterField(
            model_name='documentpage',
            name='body',
            field=wagtail.fields.StreamField([('document', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.RichTextBlock(required=True)), ('language', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(required=True)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=True))]), label='Languages', required=True)), ('year_tags', wagtail.blocks.ChoiceBlock(choices=[('2023', '2023'), ('2024', '2024'), ('2022', '2022')], label='Year Tags', required=False)), ('publication_type_tags', wagtail.blocks.ChoiceBlock(choices=[('research', 'Research'), ('information', 'Information'), ('submission', 'Submission')], label='Publication Type Tags', required=False))]))], blank=True, use_json_field=None),
        ),
    ]
