# Generated by Django 3.2.10 on 2023-12-14 11:24

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cib_documents', '0006_alter_documentpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpage',
            name='publication_select_component',
            field=wagtail.fields.StreamField([('document', wagtail.blocks.StructBlock([('select_title', wagtail.blocks.CharBlock(max_length=50)), ('select_hint_text', wagtail.blocks.CharBlock(max_length=50, required=False)), ('select_default_option_value', wagtail.blocks.CharBlock(max_length=50))]))], blank=True, use_json_field=None),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='year_select_component',
            field=wagtail.fields.StreamField([('document', wagtail.blocks.StructBlock([('select_title', wagtail.blocks.CharBlock(max_length=50)), ('select_hint_text', wagtail.blocks.CharBlock(max_length=50, required=False)), ('select_default_option_value', wagtail.blocks.CharBlock(max_length=50))]))], blank=True, use_json_field=None),
        ),
    ]
