# Generated by Django 3.2.10 on 2023-12-14 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cib_documents', '0007_documentpage_last_published_custom'),
        ('cib_documents', '0009_auto_20231214_1149'),
    ]

    operations = [
    ]
