# Generated by Django 3.2.10 on 2023-12-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cib_documents', '0009_auto_20231214_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttypetag',
            name='locale',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
