# Generated by Django 3.2.10 on 2024-01-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cib_documents', '0012_documentpage_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpage',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
