# Generated by Django 3.2.10 on 2024-01-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cib_documents', '0013_alter_documentpage_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpage',
            name='left_nav_title',
            field=models.TextField(null=True),
        ),
    ]
