# Generated by Django 3.2.10 on 2024-01-12 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_jobsvacanciesandlatestnewssnippet'),
        ('cib_documents', '0014_documentpage_left_nav_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpage',
            name='jobvacancy_latestnews_snippet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='utils.jobsvacanciesandlatestnewssnippet'),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='news_letter_signup_cta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='utils.newslettersignupctasnippet'),
        ),
    ]
