# Generated by Django 3.2.10 on 2024-01-18 10:08

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cib_documents', '0015_auto_20240112_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentpage',
            name='summary',
            field=models.TextField(blank=True, help_text='Summary text to appear under search results', null=True),
        ),
    ]
